---
# Constants
UNIT_TEST_CONFIG: &UNIT_TEST_CONFIG
  timeout_in_minutes: 5
  agents:
    queue: ruby-2-7-mysql
    ruby: 2.7
bundle_install_commands: &bundle_install_commands
- bundle install --without development
- bundle exec appraisal install --without development
common_env: &common_env
  USE_MYSQL_DB: "true"
  RAILS_ENV: "test"

# Pipeline Steps
steps:
- label: ":rails: Current Unit Tests"
  <<: *UNIT_TEST_CONFIG
  env:
    <<: *common_env
    JUNIT_OUTPUT: test/reports/current/report.xml
  commands:
  - bundle install --without development
  - bundle exec rake db:setup
  - bundle exec rake test
  artifact_paths:
  - test/reports/current/*.xml

- label: ":rails: {{ matrix.appraisal }} Unit Tests"
  matrix:
    setup:
      appraisal:
      - rails-5
      - rails-6
  <<: *UNIT_TEST_CONFIG
  env:
    <<: *common_env
    JUNIT_OUTPUT: "test/reports/{{ matrix.appraisal }}/report.xml"
  commands:
  - *bundle_install_commands
  - bundle exec rake db:setup
  - "bundle exec appraisal {{ matrix.appraisal }} rake test"
  artifact_paths:
  - "test/reports/{{ matrix.appraisal }}/*.xml"

# Test Summary Annotate Plugin
- wait: ~
  continue_on_failure: true

- label: Test Summary Annotate
  timeout_in_minutes: 5
  agents:
    queue: ruby-2-6
  plugins:
  - bugcrowd/test-summary#master:
      inputs:
      - label: Current Unit Tests
        artifact_path: test/reports/current/report.xml
        type: junit
      - label: Rails 5 Unit Tests
        artifact_path: test/reports/rails-5/report.xml
        type: junit
      - label: Rails 6 Unit Tests
        artifact_path: test/reports/rails-6/report.xml
        type: junit
      run_without_docker: true
